# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(208, 266)
        self.tedit_prefix = QtWidgets.QTextEdit(parent=Dialog)
        self.tedit_prefix.setGeometry(QtCore.QRect(30, 30, 141, 25))
        self.tedit_prefix.setAcceptDrops(True)
        self.tedit_prefix.setObjectName("tedit_prefix")
        self.spin_photo_count = QtWidgets.QSpinBox(parent=Dialog)
        self.spin_photo_count.setGeometry(QtCore.QRect(75, 80, 51, 24))
        self.spin_photo_count.setAcceptDrops(True)
        self.spin_photo_count.setMinimum(1)
        self.spin_photo_count.setMaximum(20)
        self.spin_photo_count.setProperty("value", 10)
        self.spin_photo_count.setObjectName("spin_photo_count")
        self.spin_combo_count = QtWidgets.QSpinBox(parent=Dialog)
        self.spin_combo_count.setGeometry(QtCore.QRect(70, 130, 61, 24))
        self.spin_combo_count.setAcceptDrops(True)
        self.spin_combo_count.setMinimum(1)
        self.spin_combo_count.setMaximum(1000)
        self.spin_combo_count.setProperty("value", 125)
        self.spin_combo_count.setObjectName("spin_combo_count")
        self.btn_save_to_file = QtWidgets.QPushButton(parent=Dialog)
        self.btn_save_to_file.setGeometry(QtCore.QRect(20, 220, 171, 32))
        self.btn_save_to_file.setObjectName("btn_save_to_file")
        self.tedit_freezed_numbers = QtWidgets.QTextEdit(parent=Dialog)
        self.tedit_freezed_numbers.setGeometry(QtCore.QRect(30, 185, 151, 25))
        self.tedit_freezed_numbers.setAcceptDrops(True)
        self.tedit_freezed_numbers.setObjectName("tedit_freezed_numbers")
        self.lbl_prefix = QtWidgets.QLabel(parent=Dialog)
        self.lbl_prefix.setGeometry(QtCore.QRect(22, 10, 171, 16))
        self.lbl_prefix.setObjectName("lbl_prefix")
        self.lbl_photo_count = QtWidgets.QLabel(parent=Dialog)
        self.lbl_photo_count.setGeometry(QtCore.QRect(25, 60, 161, 16))
        self.lbl_photo_count.setObjectName("lbl_photo_count")
        self.lbl_combo_count = QtWidgets.QLabel(parent=Dialog)
        self.lbl_combo_count.setGeometry(QtCore.QRect(26, 110, 171, 16))
        self.lbl_combo_count.setObjectName("lbl_combo_count")
        self.lbl_freezed_numbers = QtWidgets.QLabel(parent=Dialog)
        self.lbl_freezed_numbers.setGeometry(QtCore.QRect(40, 160, 131, 16))
        self.lbl_freezed_numbers.setObjectName("lbl_freezed_numbers")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tedit_prefix.setPlaceholderText(_translate("Dialog",
                                                        "Например: лес/дом"))
        self.btn_save_to_file.setText(_translate("Dialog",
                                                 "Сгенерировать в файл"))
        self.tedit_freezed_numbers.setPlaceholderText(_translate(
            "Dialog", "Например: 1, 3"))
        self.lbl_prefix.setText(_translate("Dialog",
                                           "Префикс (название пути)"))
        self.lbl_photo_count.setText(_translate("Dialog",
                                                "Количество фотографий"))
        self.lbl_combo_count.setText(_translate("Dialog",
                                                "Количество комбинаций"))
        self.lbl_freezed_numbers.setText(_translate("Dialog",
                                                    "Заморозить цифры"))
